### PR TITLE
first step

### PR DESCRIPTION
**Pull request by int3ks**
maybe you like to add the androidproject (its just a template at the moment.)
to the main project ?

i had to remove the "JetBrains.Annotations" ,"Trace.Warn" and  SignAssembly

because else i cant build the solution ??? (missing key and inkompatibility with Xamarin.)

the goal could be to edit the aktiv profile with your phone on the go ;o)

have fun
inteks

### CODE REVIEW

**Review by MaDc0wUSP — COMMENTED** [review]
Wicked!

**Comment by int3ks** [comment]
Error decrypting file.
Command exited with code 3

i dont have the keys ?!?


image

**Comment by TBXin** [comment]
> i dont have the keys ?!?

Yes, you do not have them.
This is our private keys which are will not be published.

I'd recommend to you create separate project/rep/so on and continue creation of your "android configuration" there.

**Comment by int3ks** [comment]
I did not want to say that I want your keys.
Just wanted to note that the ci can not build because of that.

i just wanted to help to start an android port.. :)

**Comment by TBXin** [comment]
> Just wanted to note that the ci can not build because of that.

CI can, but not for pull requests. This is a service policy.

> i just wanted to help to start an android port.. :)

Thank you, but better to make a separate project at least at this point.

**Comment by int3ks** [comment]
if you want. no problem...

but for compatibility reason , can you keep out 
using NLog;
using JetBrains.Annotations;

out of NCore project. ?

**Comment by TBXin** [comment]
Why i should remove packages that i am using?
Android project is a your project, not our and i don't know how do you create them.

Until I decide that I will support the application for android, I will not change or merge anything related to it.

**Comment by int3ks** [comment]
just to make it easier to merge some time. if you decide to do so,
i.e.  JetBrains.Annotations; is not really needed. it just cosmetic
and instead of nlog you can just use debug.writeline. 
Was only a suggestion.

**Pull request closed without merging**
