### PR TITLE
Add Patch to Hide unused Graphics

### PR DESCRIPTION
**Pull request by bluenazgul**
Wismec RX200S FW 4.10 Patch to Hide unused Graphics

### CODE REVIEW

**Comment by bluenazgul** [comment]
There are possible a few more Graphics to hide.

The following Number Graphics are used for:
0x01 - 0x0A -> Battery %
0x0B - 0x14 -> Puff Counter / Amp / Ohm
0x1F - 0x28 -> TCR Set
0x29 - 0x32 -> Battery Voltage
0x52 - 0x5B -> Firmware Version

**Comment by bluenazgul** [comment]
0x3D - 0x47 ->Volt/Watt
0x5C - 0x66 -> Watt/Temp

**Comment by TBXin** [comment]
I don't think that there are so much unused glyphs...
Did you test all cases? Checked all references in the code?
Also, really unused glyphs stay visible after applying this patch...

**Comment by bluenazgul** [comment]
I tested all cases with this patch on my RX200S - i left a few realy unused glyphs and glyphs where iam not 100% sure

**Comment by bluenazgul** [comment]
Iam not sure about:
0xD2
0xD3
0xD8
0xD9
0xDA
0xDB
0xDE
0xDC
0xDD
0xDF
0xF1
0xF7
0xF8

Iam sure the this glyphs are unused too:
0xDE
0xE0
0xE1
0xE2
0xE3
0xFC
0xFD

Also the Logo 0x101 is sadly unused on the RX200S

**Comment by TBXin** [comment]
> I tested all cases with this patch on my RX200S

Realy? You changed every glyphs and look for artifacts on the screen?
I saw that you hide many numbers and fonts. Did you know that they can be used when you scrolling power / temperature from min to max?
Also, some procedures do not uses image table and going directly to the image data.

**Comment by bluenazgul** [comment]
I changed all the Glyphs that are hidden with this Patch - this is the first "hack" i did to an Firmware myself.

I have also published an CFW with this Patch in the biggest german Facebook Group for the Wismec Reuleuax two days ago, there are no knows issues yet.

**Comment by deddy84** [comment]
please can you add various patches (like digital screensaver watch, max brightness etc...) for eGrip2 v4.03? 
I am not able to create them...

**Pull request closed without merging**
