### PR TITLE
More Cuboid 3.13 patches

### PR DESCRIPTION
**Pull request by ieatacid**
Updated the rest of the patches that I could.  If anyone can tell me how
to find the entry point of a firmware image so I can load it in IDA
please contact me on gmail or twitter @ieatacid.  Thanks!

### CODE REVIEW

**Comment by ieatacid** [comment]
If anyone reading this can tell me how to find the entry point of a decrypted firmware image so I can load it in IDA please contact me on gmail or twitter @ieatacid.  It would be much appreciated :)

**Comment by TBXin** [comment]
What does you mean by images entry point?

You can look at Definitions.xml file, which contains image table offsets for each supported firmwares.
Each image table is a int32 array. Each value is an absolute offset in the firmware to the image body.

Image structure:
byte: width
byte: height
byte array: data

For SSD1306 display (block 1) data length calculated as: Width \* ((Height + 7) / 8)
For SSD1327 display (block 2) data length calculated as: (Width + 7) / 8 \* Height

Reading and writing algorithms you can look here:
https://github.com/TBXin/NFirmwareEditor/blob/master/src/NFirmware/FirmwareImage1Metadata.cs
https://github.com/TBXin/NFirmwareEditor/blob/master/src/NFirmware/FirmwareImage2Metadata.cs

**Comment by ieatacid** [comment]
The location (offset) of the executable code. The processor type is "ARM [big endian]" in IDA, but since IDA can't find the location of the executable code you have to specify the location. I wanted to work on the rest of the patches, but without seeing some disassembled code it's hard to figure out what the other patches are changing (and how to correctly update them).

**Comment by TBXin** [comment]
IDA can disassemble firmware even without entry point.

And processor type is ARM [Little endian]

**Comment by ieatacid** [comment]
Oh, that's great! Do you just leave everything set to default, like when it pops up the window with ROM address and size?

**Comment by TBXin** [comment]
Yeap, just select ARM (Little Endian)

**Comment by ieatacid** [comment]
Awesome, thanks!

**Pull request closed without merging**
